INSERT INTO make (id, name)
VALUES (UUID(), 'Datsun'),
       (UUID(), 'Tesla'),
       (UUID(), 'Aston Martin'),
       (UUID(), 'Maserati'),
       (UUID(), 'Polaris'),
       (UUID(), 'Rolls-Royce'),
       (UUID(), 'Eagle'),
       (UUID(), 'Lamborghini'),
       (UUID(), 'Freightliner'),
       (UUID(), 'Panoz'),
       (UUID(), 'Ski-do'),
       (UUID(), 'Karma'),
       (UUID(), 'Can Am'),
       (UUID(), 'Lotus'),
       (UUID(), 'Acura'),
       (UUID(), 'Alfa Romeo'),
       (UUID(), 'Audi'),
       (UUID(), 'BMW'),
       (UUID(), 'Buick'),
       (UUID(), 'Cadillac'),
       (UUID(), 'Chevrolet'),
       (UUID(), 'Chrysler'),
       (UUID(), 'Dodge'),
       (UUID(), 'FIAT'),
       (UUID(), 'Fisker'),
       (UUID(), 'Ford'),
       (UUID(), 'GMC'),
       (UUID(), 'Honda'),
       (UUID(), 'HUMMER'),
       (UUID(), 'Hyundai'),
       (UUID(), 'Infiniti'),
       (UUID(), 'Isuzu'),
       (UUID(), 'Jaguar'),
       (UUID(), 'Jeep'),
       (UUID(), 'Kia'),
       (UUID(), 'Land Rover'),
       (UUID(), 'Lexus'),
       (UUID(), 'Lincoln'),
       (UUID(), 'Mazda'),
       (UUID(), 'Mercedes-Benz'),
       (UUID(), 'Mercury'),
       (UUID(), 'MINI'),
       (UUID(), 'Mitsubishi'),
       (UUID(), 'Nissan'),
       (UUID(), 'Oldsmobile'),
       (UUID(), 'Plymouth'),
       (UUID(), 'Pontiac'),
       (UUID(), 'Porsche'),
       (UUID(), 'Ram'),
       (UUID(), 'Saab'),
       (UUID(), 'Saturn'),
       (UUID(), 'Scion'),
       (UUID(), 'Smart'),
       (UUID(), 'Spyker'),
       (UUID(), 'Subaru'),
       (UUID(), 'Suzuki'),
       (UUID(), 'Toyota'),
       (UUID(), 'Volkswagen'),
       (UUID(), 'Volvo'),
       (UUID(), 'Harley Davidson'),
       (UUID(), 'Ferrari'),
       (UUID(), 'Genesis'),
       (UUID(), 'Maybach'),
       (UUID(), 'MG'),
       (UUID(), 'Hino'),
       (UUID(), 'Bentley'),
       (UUID(), 'AM General'),
       (UUID(), 'Yamaha'),
       (UUID(), 'Geo'),
       (UUID(), 'McLaren'),
       (UUID(), 'Daewoo'),
       (UUID(), 'Kawasaki'),
       (UUID(), 'International')